### ISSUE TITLE
Thaumcraft - Thaumometer unable to scan following any movement.

### ISSUE THREAD

**Issue by kuar-z** [Techjar/VivecraftForgeExtensions#1]
When combined with Thaumcraft and Vivecraft, Thaumometer appears to scan an invisible entity encompassing the player space instead of the block being pointed at. I have replicated this issue with just Thaumcraft and Forge extensions on a clean install.

**Comment by Techjar** [comment]
I think I might know what's going on here, I'm just not entirely sure how to fix it.

**Comment by Techjar** [comment]
The bounding boxes now no longer exist (actually, they're at the world origin), I tested TC and it works fine now.
