### ISSUE TITLE
Non vive players screen going purple when vive player is attacked.

### ISSUE THREAD

**Issue by feedbackandnoise** [Techjar/VivecraftForgeExtensions#2]
I'm having an issue with my forge vivecraft server where anytime I get attacked the non vive person I'm playing with's screen goes purple and they can no longer see anything until they disconnect and reconnect.

I've narrowed the issue down to this plugin.

**Comment by Techjar** [comment]
Looking into this now. Seems the value I'm returning from shouldRenderPass() is not what I should be returning.

**Comment by feedbackandnoise** [comment]
Let me know if you need any logs/data from my end.

**Comment by Techjar** [comment]
Easy fix, just took a while before pushing as I had to fix another issue first.
