### ISSUE TITLE
Modpack License

### ISSUE THREAD

**Issue by Aubron** [Techjar/VivecraftForgeExtensions#3]
Do others have permission to redistribute this in modpacks like those on the FeedTheBeast Launcher? We'd like to add this to our private modpack (The AlienMC Pack, running on the official /r/feedthebeast subreddit server), so that Vive clients can join our public server.

**Comment by Techjar** [comment]
Yes, throw it in any mod pack you want, doesn't matter to me. Just don't go claiming you made the mod or anything stupid like that. I'll add this to the readme.
